version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: root
    volumes:
      - vesa_arango_data:/var/lib/arangodb3
    networks:
      - app-network

  backend:
    build:
      context: ./BACKEND
    ports:
      - "5000:5000"
    environment:
      ARANGO_URL: http://arangodb:8529
      ARANGO_DB_NAME: vesa2db
      ARANGO_USER: root
      ARANGO_PASS: root
      NODE_PORT: 5000
    depends_on:
      - arangodb
    networks:
      - app-network
    restart: on-failure

  frontend:
    build:
      context: ./FRONTEND
      args:
        VITE_API_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  vesa_arango_data:
